"""静态数据：产品匹配规则、时区表、商务文化指南"""

PRODUCT_RULES = [
    ('阻燃面料（FR protective fabrics）', '⭐ 优先',
     ['fr fabric', '阻燃面料', 'flame retardant fabric', 'fire retardant',
      'nfpa 2112', 'en iso 11612', 'en11612',
      'arc flash', '电弧', '电弧防护', '焊接', 'welding', 'en iso 11611',
      '工装面料', 'workwear fabric', 'firefighter', '消防服',
      '防护服面料', '阻燃工装', 'fr clothing',
      '热防护', 'thermal protective', '高温防护']),
    ('防切割面料（Cut-resistant fabrics）', '⭐ 优先',
     ['cut resistant fabric', '防切割面料', '防割面料', 'en388',
      'ansi cut', 'protective fabric', '防护面料',
      '抗切割', '耐磨面料', 'anti cut', 'cut resistant textile',
      '高强面料', 'high strength fabric']),
    ('防切割纱线（Cut-resistant yarns）', '⭐ 优先',
     ['cut resistant yarn', '防切割纱线', 'hppe yarn', '芳纶纱',
      '针织纱', '手套纱', 'knitting yarn', 'glove yarn',
      '包芯纱', 'core spun', '复合纱', 'composite yarn',
      '防割纱', '抗切割纱线']),
    ('阻燃耐高温纱线（FR / aramid yarns）', '高',
     ['fr yarn', '阻燃纱线', '耐高温纱线', 'heat resistant yarn',
      '芳纶', 'aramid', 'meta-aramid', '间位芳纶', '1313',
      '对位芳纶', '1414', 'para-aramid',
      '预氧丝', 'panox', '预氧化', '氧化丝',
      '改性腈纶', 'modacrylic', '阻燃腈纶',
      '混纺纱', '阻燃混纺', 'fr blended']),
    ('防切割手套（Cut-resistant gloves）', '中',
     ['手套', 'glove', 'hand protection', '护具', 'knitted glove',
      '机械防护', '作业防护', '劳保手套', '安全手套',
      '防割手套', 'cut resistant glove', 'working glove']),
    ('防割袖套（Cut-resistant sleeves）', '中',
     ['袖套', 'sleeve', 'arm protection', '手臂防护',
      '护袖', 'arm guard', '安全袖套']),
    ('防割服（Cut-resistant clothing）', '中',
     ['防护服', 'protective clothing', 'coverall', '工装', '安全服',
      '防割服', 'cut resistant clothing', '防刺服',
      '抗割服装']),
    ('工业缝纫线（Industrial sewing thread）', '中',
     ['缝纫线', 'sewing thread', 'thread', '阻燃缝纫',
      '芳纶缝纫线', 'aramid thread', '高强缝纫线']),
]

TIMEZONE_MAP = {
    # (base_utc, has_dst, dst_utc, label)
    'germany': (1, True, 2, '德国'), '德国': (1, True, 2, '德国'),
    'france': (1, True, 2, '法国'), '法国': (1, True, 2, '法国'),
    'italy': (1, True, 2, '意大利'), '意大利': (1, True, 2, '意大利'),
    'spain': (1, True, 2, '西班牙'), '西班牙': (1, True, 2, '西班牙'),
    'netherlands': (1, True, 2, '荷兰'), '荷兰': (1, True, 2, '荷兰'),
    'belgium': (1, True, 2, '比利时'), '比利时': (1, True, 2, '比利时'),
    'sweden': (1, True, 2, '瑞典'), '瑞典': (1, True, 2, '瑞典'),
    'norway': (1, True, 2, '挪威'), '挪威': (1, True, 2, '挪威'),
    'finland': (2, True, 3, '芬兰'), '芬兰': (2, True, 3, '芬兰'),
    'denmark': (1, True, 2, '丹麦'), '丹麦': (1, True, 2, '丹麦'),
    'poland': (1, True, 2, '波兰'), '波兰': (1, True, 2, '波兰'),
    'czech': (1, True, 2, '捷克'), '捷克': (1, True, 2, '捷克'),
    'austria': (1, True, 2, '奥地利'), '奥地利': (1, True, 2, '奥地利'),
    'switzerland': (1, True, 2, '瑞士'), '瑞士': (1, True, 2, '瑞士'),
    'uk': (0, True, 1, '英国'), '英国': (0, True, 1, '英国'),
    'portugal': (0, True, 1, '葡萄牙'), '葡萄牙': (0, True, 1, '葡萄牙'),
    'usa': (-5, True, -4, '美国'), '美国': (-5, True, -4, '美国'),
    'united states': (-5, True, -4, '美国'),
    'canada': (-5, True, -4, '加拿大'), '加拿大': (-5, True, -4, '加拿大'),
    'mexico': (-6, False, -6, '墨西哥'), '墨西哥': (-6, False, -6, '墨西哥'),
    'australia': (10, True, 11, '澳大利亚'), '澳大利亚': (10, True, 11, '澳大利亚'),
    'japan': (9, False, 9, '日本'), '日本': (9, False, 9, '日本'),
    'korea': (9, False, 9, '韩国'), '韩国': (9, False, 9, '韩国'),
    'india': (5.5, False, 5.5, '印度'), '印度': (5.5, False, 5.5, '印度'),
    'brazil': (-3, False, -3, '巴西'), '巴西': (-3, False, -3, '巴西'),
    'turkey': (3, False, 3, '土耳其'), '土耳其': (3, False, 3, '土耳其'),
    'russia': (3, False, 3, '俄罗斯'), '俄罗斯': (3, False, 3, '俄罗斯'),
    'colombia': (-5, False, -5, '哥伦比亚'), '哥伦比亚': (-5, False, -5, '哥伦比亚'),
    'vietnam': (7, False, 7, '越南'), '越南': (7, False, 7, '越南'),
}

CULTURE_GUIDE = {
    'germany': {
        'weekend': '周六日',
        'best_days': '周二至周四',
        'avoid_days': '周五下午（很多人提前下班）',
        'language': '德语 / 英语（商务英语可通）',
        'etiquette': [
            '邮件开头用 "Sehr geehrte" + 姓，关系熟后用 "Guten Tag"',
            '德国人重视头衔（Dr./Prof.），称呼别省略',
            '报价要精准、数据要严谨，德国人对模糊表述反感',
            '决策链长且层级分明，不要期望快速成交',
            '见面准时是基本要求，迟到是大忌',
        ],
        'taboos': [
            '别拿二战、纳粹当话题',
            '别跟德国人比价格，他们更看重质量和技术参数',
            '私生活（收入、家庭）不是商务话题',
        ],
        'holidays': '5月： Christi Himmelfahrt（耶稣升天节） | 6月：Pfingsten（圣灵降临节）',
    },
    'france': {
        'weekend': '周六日',
        'best_days': '周二至周四',
        'avoid_days': '周五下午、周一上午、8月全月（全国放假）',
        'language': '法语优先，英语也可',
        'etiquette': [
            '开头用法语问候 "Bonjour" 很重要',
            '法国人重视正式感，邮件不要太随意',
            '8月大部分法国公司关门休假，别在这个月发开发信',
            '商务沟通偏向自上而下，找对决策人比磨中间人有效',
        ],
        'taboos': [
            '别一上来就谈钱，先建立关系',
            '避免英语与法语之间的语言优越感争论',
            '不要在邮件中用过多的销售套话',
        ],
        'holidays': '5月：Fête du Travail（劳动节） | 7/14：国庆日 | 8月：全国暑假',
    },
    'italy': {
        'weekend': '周六日',
        'best_days': '周二至周四',
        'avoid_days': '周五下午、8月 Ferragosto 前后',
        'language': '意大利语 / 英语',
        'etiquette': [
            '意大利人关系导向，先建立信任再谈业务',
            '邮件回复可能不快，不代表没兴趣',
            '八月基本不工作（Ferragosto），别催',
            '意大利中小企业多，老板直接决策',
        ],
        'taboos': [
            '别拿南北差异开玩笑',
            '别跟意大利人比披萨/意面',
            '邮件别太生硬，加点人情味',
        ],
        'holidays': '8月：Ferragosto（全国休假） | 4月：Pasquetta（复活节周一）',
    },
    'spain': {
        'weekend': '周六日',
        'best_days': '周二至周四',
        'avoid_days': '周五下午、8月、Siesta 时间（14:00-16:00）别打电话',
        'language': '西班牙语 / 英语',
        'etiquette': [
            '西班牙也有午休文化，下午2点到4点不适宜打电话',
            '关系建立很重要，初次邮件不要太硬',
            '8月份很多公司关门或不处理新业务',
            '决策比北欧国家慢，正常跟进节奏即可',
        ],
        'taboos': [
            '别问加泰罗尼亚独立等政治话题',
            '别催太紧，西班牙人有自己的节奏',
        ],
        'holidays': '8月：全国暑假 | 各地还有自己的守护神节',
    },
    'uk': {
        'weekend': '周六日',
        'best_days': '周二至周四',
        'avoid_days': '周五下午、Bank Holiday 长周末',
        'language': '英语',
        'etiquette': [
            '英式商务讲究礼貌和保守，不要过于热情',
            '邮件措辞要客气，多用 "please" "I was wondering"',
            '英国人决策偏谨慎，需要多次跟进',
            '善用 "understatement"（低调表达），别过分吹嘘产品',
        ],
        'taboos': [
            '避免谈论脱欧政治话题',
            '不要混淆英国/英格兰/苏格兰的概念',
            '别用美式拼写（color→colour, center→centre）',
            '问工资年龄是粗鲁的',
        ],
        'holidays': '5月：Early May BH / Spring BH | 8月：Summer BH（各地不同）',
    },
    'usa': {
        'weekend': '周六日',
        'best_days': '周一至周四',
        'avoid_days': '周末尽量不打扰、感恩节/圣诞节前后',
        'language': '英语（美式）',
        'etiquette': [
            '美国决策快，直接说明产品价值和差异化优势',
            '美国人喜欢直奔主题，邮件前两行就要抓住注意力',
            '称呼用 First name（名字）即可，不用太正式',
            '感恩节（11月第4个周四）到元旦期间效率低',
        ],
        'taboos': [
            '避免政治话题（大选、枪支、堕胎等）',
            '别过度承诺交付时间',
            '自夸要适度，有数据支撑更好',
        ],
        'holidays': '5月：Memorial Day | 7/4：独立日 | 11月：Thanksgiving | 12月：圣诞+新年',
    },
    'turkey': {
        'weekend': '周六日（周五下午有些公司早退）',
        'best_days': '周日至周四',
        'avoid_days': '周五下午、宗教节日（开斋节/古尔邦节）',
        'language': '土耳其语 / 英语',
        'etiquette': [
            '土耳其人关系导向，信任比价格重要',
            '邮件开头加 "Sayın" + 名字表示尊重',
            '开斋节和古尔邦节前后一周基本不办公',
            '谈判要有耐心，土耳其人喜欢商量',
        ],
        'taboos': [
            '不要批评土耳其的政治或宗教',
            '不要使用与希腊有关的比较',
            '避免左手递名片或物品',
        ],
        'holidays': 'Ramazan Bayrami（开斋节） | Kurban Bayrami（古尔邦节）| 日期每年变动',
    },
    'india': {
        'weekend': '周六日（部分公司周日单休）',
        'best_days': '周一到周五',
        'avoid_days': '排灯节前后、洒红节',
        'language': '英语（印式英语可通）',
        'etiquette': [
            '印度英语口音重，邮件沟通比电话更清晰',
            '印度人习惯讨价还价，报价可以留空间',
            '决策者通常是老板或总监级别',
            '关系建立很重要，先聊几句再谈业务',
        ],
        'taboos': [
            '不要用左手递东西',
            '避免谈巴基斯坦等政治敏感话题',
            '牛在印度是神圣的，别拿牛肉开玩笑',
            '不要催促印度人做决定，他们喜欢多方比较',
        ],
        'holidays': '10-11月：Diwali（排灯节，全国放假）| 3月：Holi（洒红节）',
    },
    'poland': {
        'weekend': '周六日',
        'best_days': '周一至周四',
        'avoid_days': '周五下午、圣诞节/复活节前后',
        'language': '波兰语 / 英语（年轻人英语不错）',
        'etiquette': [
            '波兰商务偏正式，邮件开头用 "Szanowny Pan/Pani" + 姓',
            '报价和条款要写清楚，波兰人注重细节',
            '决策偏慢，需要多轮沟通',
        ],
        'taboos': [
            '不要提俄波关系',
            '别把波兰称为东欧（他们更认同中欧）',
        ],
        'holidays': '5/1：劳动节 | 5/3：宪法日 | Boze Cialo（基督圣体节，日期不定）',
    },
    'portugal': {
        'weekend': '周六日',
        'best_days': '周二至周四',
        'avoid_days': '8月、周五下午、狂欢节前后',
        'language': '葡萄牙语 / 英语',
        'etiquette': [
            '葡国人友好但商务节奏偏慢',
            '建立关系比直接谈价格更有效',
            '8月基本不办公',
        ],
        'taboos': [
            '别拿西班牙和葡萄牙做比较，他们不喜欢被说像西班牙',
            '避免谈论前殖民地话题',
        ],
        'holidays': '6月：Dia de Portugal | 狂欢节（2月）| 8月：全国休假',
    },
    'belgium': {
        'weekend': '周六日',
        'best_days': '周二至周四',
        'avoid_days': '周五下午、7月中旬-8月',
        'language': '荷兰语（弗拉芒）/ 法语 / 英语',
        'etiquette': [
            '比利时分荷语区和法语区，注意对方所在区域',
            '商务偏保守和正式，比法国人更务实',
            '决策偏谨慎，需要耐心跟进',
        ],
        'taboos': [
            '别问客户是弗拉芒人还是瓦隆人（敏感）',
            '避免把比利时和法国混为一谈',
        ],
        'holidays': '7/21：国庆日 | 7-8月：各地暑假',
    },
    'colombia': {
        'weekend': '周六日',
        'best_days': '周二至周四',
        'avoid_days': '周一（很多人周末连休）、周五下午、12月',
        'language': '西班牙语 / 英语（商务英语有限）',
        'etiquette': [
            '哥伦比亚人关系导向，先建立信任',
            '邮件用西班牙语开头更有诚意',
            '决策偏慢，不要催太紧',
        ],
        'taboos': [
            '避免讨论毒品/游击队等敏感话题',
            '12月基本在过节，效率低',
        ],
        'holidays': '12月：圣诞+新年长假',
    },
    'korea': {
        'weekend': '周六日',
        'best_days': '周二至周四',
        'avoid_days': '春节/中秋前后各一周',
        'language': '韩语 / 英语（书面沟通更清晰）',
        'etiquette': [
            '韩国人重视等级和尊重，邮件语气要礼貌正式',
            '决策通常需要上报，不会当场拍板',
            '关系（인맥）很重要，但初次邮件保持专业即可',
            '避免在邮件中过于直接批评或否定',
        ],
        'taboos': [
            '避免谈日本殖民历史',
            '不要在第一次沟通中催促决策',
            '对长辈/上级用敬语，邮件中注意尊重语气',
        ],
        'holidays': '1-2月：Seollal（春节）| 9-10月：Chuseok（中秋）| 日期每年变动',
    },
    'vietnam': {
        'weekend': '周六日',
        'best_days': '周二至周六上午',
        'avoid_days': '春节（Tet）前后两周',
        'language': '越南语 / 英语',
        'etiquette': [
            '越南人关系导向，先建立信任比较好谈',
            '春节（Tet）是最大节日，前后两周不办公',
            '报价可以留余地，越南喜欢友好协商',
        ],
        'taboos': [
            '避免谈中越历史问题',
            '不要公开批评越南政府',
            '送礼要注意分寸，避免让人觉得是贿赂',
        ],
        'holidays': '1-2月：Tet（春节，最重要节日）| 4/30：统一日 | 5/1：劳动节',
    },
}

CN_COUNTRY_MAP = {
    '德国': 'germany', '法国': 'france', '意大利': 'italy',
    '西班牙': 'spain', '英国': 'uk', '荷兰': 'netherlands',
    '比利时': 'belgium', '瑞典': 'sweden', '挪威': 'norway',
    '芬兰': 'finland', '丹麦': 'denmark', '波兰': 'poland',
    '捷克': 'czech', '奥地利': 'austria', '瑞士': 'switzerland',
    '美国': 'usa', '加拿大': 'canada', '墨西哥': 'mexico',
    '澳大利亚': 'australia', '日本': 'japan', '韩国': 'korea',
    '印度': 'india', '巴西': 'brazil', '土耳其': 'turkey',
    '俄罗斯': 'russia', '葡萄牙': 'portugal', '哥伦比亚': 'colombia',
    '越南': 'vietnam',
}
